welcome:
  message: "lel"
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://www.jdowd.name:3306/test
    username: jdowd
    password: x^907Mjnf0
server:
  port: 8888